### ISSUE TITLE
Image missing

### ISSUE THREAD

**Issue by eurica** [Unstructured-IO/docs#12]
Looks like https://unstructured-io.github.io/unstructured/apis/imgs/paid_api/opt-in.png is 404-ing

https://github.com/Unstructured-IO/docs/blob/d0db16a2a0dc6566e72869f75f92a3f5f933c131/api-reference/api-services/saas-api-development-guide.mdx?plain=1#L129

**Comment by Paul-Cornell** [comment]
Thanks for the feedback and sorry for the delay in responding. I just checked the current builds, and the article has been recently updated such that this image is no longer referenced.
