### ISSUE TITLE
The link to the dropbox source connector example is invalid

### ISSUE THREAD

**Issue by WHALEEYE** [Unstructured-IO/docs#128]
In the file `snippets/sc-shared-text/dropbox.mdx`, an example file of dropbox_token.py is referenced with the path https://github.com/Unstructured-IO/unstructured/blob/main/examples/ingest/dropbox/dropbox_token.py. However, this path seems like invalid.

**Comment by Paul-Cornell** [comment]
Thanks for the feedback. This should be addressed as part of https://github.com/Unstructured-IO/docs/pull/140.
