### ISSUE TITLE
docs: missing example for HuggingFaceEmbeddingEncoder

### ISSUE THREAD

**Issue by bplunkert** [Unstructured-IO/docs#42]
The documentation for HuggingFaceEmbeddingEncoder in [embedding.rst](https://github.com/Unstructured-IO/unstructured/blob/9fea85dc210a52f0aaafecad97a43fd708a98304/docs/source/core/embedding.rst?plain=1#L83-L85) refers to a code block with example usage, but this block is missing for this encoder. Similar examples are given for other encoders.

**Comment by MKhalusova** [comment]
Fixed in the docs with https://github.com/Unstructured-IO/docs/pull/44
