### ISSUE TITLE
Documentation for Ingestion of wikipedia

### ISSUE THREAD

**Issue by debasisdwivedy** [Unstructured-IO/docs#51]
Hi,

Please find the below URL:

https://unstructured-io.github.io/unstructured/ingest/source_connectors/wikipedia.html

The explanation says "Connect **Airtable** to your preprocessing pipeline, and batch process all your documents using unstructured-ingest to store structured outputs locally on your filesystem." which i think is wrong.

Regards

**Comment by MKhalusova** [comment]
The docs have moved to a new URL, and this has been addressed there: 
https://docs.unstructured.io/api-reference/ingest/source-connectors/wikipedia
https://docs.unstructured.io/open-source/ingest/source-connectors/wikipedia
