### ISSUE TITLE
docs: Add docs showing users can set which OCR agent to use

### ISSUE THREAD

**Issue by Coniferish** [Unstructured-IO/docs#54]
The ability to set which OCR Agent should be used was added [here](https://github.com/Unstructured-IO/unstructured/pull/2462/files), but there is no documentation describing this (example of [user asking if this can be done](https://github.com/Unstructured-IO/unstructured/issues/2958))

**Comment by cragwolfe** [comment]
And was successfully used here:
https://github.com/Unstructured-IO/unstructured/pull/2902

**Comment by lucasalberto01** [comment]
+1

I've been using it `os.environ["OCR_AGENT"] = "unstructured.partition.utils.ocr_models.google_vision_ocr"` before `PartitionParameters` but it doesn't seem to be working.

Do you need to change something in `PartitionParameters`?

**Comment by Paul-Cornell** [comment]
OK, based on my discussions with Unstructured Engineering, you can do either of the following, as I understand it:

- Set `strategy` to `hi_res` and then set `hi_res_model_name` to one of the available models, from the list on the [Models](https://docs.unstructured.io/open-source/concepts/models) page.

Or:

- Set `strategy` to `ocr_only` to run the document through Tesseract OCR / Paddle OCR to extract text from images.

I will add this to the docs.

**Comment by Paul-Cornell** [comment]
See https://docs.unstructured.io/open-source/how-to/set-ocr-agent

**Comment by jakevollkommer** [comment]
so we can't set the OCR model in `hi_res` or `auto`? Is OCR not part of `hi_res`?

**Comment by Paul-Cornell** [comment]
No.

**Comment by jakevollkommer** [comment]
Okay, so please help me understand. The `hi_res` strategy doesn't use OCR at all, it uses a different type of model to partition the data?

Our issue is that `hi_res` doesn't do well with handwriting, we had assumed that as part of the `hi_res` strategy it uses the default OCR, I guess that isn't the case. Sounds like we should be choosing a different model then? Can you link those docs?

**Comment by Paul-Cornell** [comment]
Could you take a look at the example in https://docs.unstructured.io/open-source/how-to/set-ocr-agent, and let us know what specific questions you might have after looking at that?

**Comment by Paul-Cornell** [comment]
Also, `strategy` options are described in more depth at https://docs.unstructured.io/api-reference/api-services/partitioning.

**Comment by Paul-Cornell** [comment]
What happens when you try https://docs.unstructured.io/open-source/how-to/set-ocr-agent?

**Comment by jakevollkommer** [comment]
to clarify, we need table extraction _and_ handwriting recognition, what's the solution here?

**Comment by christinestraub** [comment]
@jakevollkommer Can you please provide your code and PDF document so I can see if I can reproduce your issue?
