### ISSUE TITLE
Please add some description for potential GPU support.

### ISSUE THREAD

**Issue by SvenSchoene** [Unstructured-IO/docs#55]
We wonder if Unstructured is benefitting from deployment on machines with GPUs?

I see some hints that Unstructured may have some GPU support:
- https://github.com/search?q=repo%3AUnstructured-IO%2Funstructured%20gpu&type=code
- Maybe it's only for PaddlePaddle that is under the Unstructured-IO umbrella? (https://github.com/Unstructured-IO/unstructured.Paddle)
- "GPU" is mentioned once in this document, but probably not directly related to using Unstructured: https://unstructured.io/blog/speeding-up-vision-transformers

Can you make it clear somehow, whether GPU is supported / if there are any benefits of deploying Unstructured on a machine with a GPU? And if so: What are those benefits? And how do we enable them explicitly?

And, on the other hand: Maybe it would make sense to clearly state somewhere that an available GPU currently makes no difference when using Unstructured.

**Comment by Paul-Cornell** [comment]
The docs were just updated to state that Unstructured does not support GPU usage with the open source library nor with the Unstructured library inside a Docker container.

- https://docs.unstructured.io/open-source/introduction/overview#common-use-cases
- https://docs.unstructured.io/open-source/installation/docker-installation#prerequisites
