### ISSUE TITLE
Update SQL destination connector docs

### ISSUE THREAD

**Issue by MKhalusova** [Unstructured-IO/docs#63]
Python example here https://docs.unstructured.io/api-reference/ingest/destination-connector/sql
is not up to date. 

The writer should be configured using `SqlWriter` similar to other examples. 

Context: https://unstructuredai.slack.com/archives/C05Q4HGDBLJ/p1717708143430909

**Comment by Paul-Cornell** [comment]
The Python example has been updated: https://docs.unstructured.io/api-reference/ingest/destination-connector/sql
